[package]
name = "everestrs"
version = "0.19.1"
edition = "2021"

[dependencies]
argh = "0.1.10"
cxx = { version = "1.0.107", features = ["c++17"] }
everestrs-build = { workspace = true }
log = { version = "0.4.20", features = ["std"] }
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.34"
thiserror = "1.0.48"

[features]
build_bazel = []
link_gcov = []

# We use this for the integration tests in this project.
[dev-dependencies]
mockall = "0.13.0"
mockall_double = "0.3.1"
