name: Bazel Build
run-name: ${{ github.actor }} is building with bazel
on: 
  pull_request: {}
  workflow_dispatch:
    inputs:
      runner:
        description: Which runner to use
        type: choice
        default: 'ubuntu-22.04'
        required: true
        options:
          - 'ubuntu-22.04'
          - 'large-ubuntu-22.04-xxl'
jobs:
  bazel-build-and-test:
    runs-on: ${{ inputs.runner || 'ubuntu-22.04' }}
    steps:
      - run: echo branch name is ${{ github.ref }}
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE.bazel', 'third-party/bazel/*') }}
      - name: Install mosquitto
        run: sudo apt-get install -y mosquitto
      - name: Build all
        run: >
          bazelisk build //...
      - name: Test all
        run: >
          bazelisk test //...
      - name: Try to run something
        run: >
          bazelisk run //:manager -- --help
