name: Linux Build
on: [workflow_dispatch, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [large-ubuntu-22.04-xxl]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: cache
          key: compile-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            compile-${{ github.ref }}-
            compile-
      - name: Checkout everest-framework
        uses: actions/checkout@v3
        with:
          path: source
      - name: Run clang-format
        uses: everest/everest-ci/github-actions/run-clang-format@v1.0.0
        with:
          source-dir: source
          extensions: hpp,cpp
          exclude: cache
      - name: Setup run scripts
        run: |
          mkdir scripts
          rsync -a source/.ci/build-kit/ scripts
      # Run from debian since alpine 3.17 does not ship lcov.
      - name: Pull docker container
        run: |
          docker pull --quiet ghcr.io/everest/build-kit-debian:latest
          docker image tag ghcr.io/everest/build-kit-debian:latest build-kit
      - name: Compile
        run: |
          docker run \
          --volume "$(pwd):/ext" \
          --name compile-container \
          build-kit run-script compile
