name: MacOS Workflow
on: [push]

jobs:
  build:
    name: ensure that everest-framework builds on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          path: everest-framework

      - name: Checkout everest-cmake
        uses: actions/checkout@v2
        with:
          repository: EVerest/everest-cmake
          path: everest-cmake
          ref: v0.1.0
      
      - name: Checkout dependency manager
        uses: actions/checkout@v2
        with:
          repository: EVerest/everest-dev-environment
          path: everest-dev-environment
          ref: v0.5.5

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build

      - name: Install dependencies with homebrew
        run: brew install openssl@1.1 boost

      - name: Install dependency manager 
        run: |
          cd everest-dev-environment/dependency_manager
          python3 -m pip install .

      - name: build
        run: |
          EVEREST_CMAKE_PATH=$(pwd)/everest-cmake
          mkdir build
          pushd build
          cmake .. \
            -DCMAKE_PREFIX_PATH=$EVEREST_CMAKE_PATH \
            -DLWS_OPENSSL_LIBRARIES="/usr/local/opt/openssl@1.1/lib/libcrypto.dylib;/usr/local/opt/openssl@1.1/lib/libssl.dylib" \
            -DLWS_OPENSSL_INCLUDE_DIRS="/usr/local/opt/openssl@1.1/include" \
            -DEVEREST_ENABLE_JS_SUPPORT=OFF \
            -DEVEREST_ENABLE_RS_SUPPORT=ON
          make -j2